### ISSUE TITLE
import bbox for qs geometry

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#29]
in lieu of providing the full geometry for countries/states/regions and all the issues involved with that we can at least provide a bbox of the geometry in order for the client to be able to zoom to a level which fully encompasses the entity.

http://geojson.org/geojson-spec.html#bounding-boxes

**Comment by riordan** [comment]
Good and YES!

Question: can we address this now (so it can be part of Erasermap 1) or does it make sense to tackle shortly thereafter and get added in a later build.

It's very useful when retargeting to another administrative area, but not necessary for launch.

**Comment by missinglink** [comment]
considering our current workload I would say that we mark it as 'high priority but not right now'

**Comment by burritojustice** [comment]
this would be nice for the leaflet plugin demo when you search for a country and end up in a vast white expanse because of refill and the default zoom level 12 (which, for the Northwest Territories, while accurate, is confusing. kansas too...)

**Comment by riordan** [comment]
What's the matter with Kansas? Or Northwest Territories?

I would love to see this. I think the question that behooves us now is "how
long will it take us to do this in 4shapes vs how long will it take us to
do WoF including this?"

If its something we can incorporate in a day or so (ideally w/o breaking
the schema), I'd love to see it happen sooner rather than later.

On Thu, Oct 8, 2015 at 1:04 PM, burritojustice <notifications@github.com>
wrote:

> this would be nice for the leaflet plugin demo when you search for a
> country and end up in a vast white expanse because of refill and the
> default zoom level 12 (which, for the Northwest Territories, while
> accurate, is confusing. kansas too...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/quattroshapes/issues/29#issuecomment-146625185>
> .
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by riordan** [comment]
This issue was moved to pelias/whosonfirst#8
